// <auto-generated />
using Beautique.DataAcess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beautique.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250316203710_SeedCategoryAndProduct")]
    partial class SeedCategoryAndProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Beautique.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Shampoos & Conditioners"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Body Washes & Soaps"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Facial Care"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Body Care"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Deodorants & Antiperspirants"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Shaving Products"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Nail Care"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Perfumes & Fragrances"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Lip Care"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Hand Care"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Hair Care"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Eye & Eyelid Care"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "Cleansing & Makeup Removal"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Organic & Bio Cosmetics"
                        });
                });

            modelBuilder.Entity("Beautique.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A premium shampoo that provides ultimate shine and smoothness.",
                            ISBN = "SW123456789",
                            ImageUrl = "",
                            ListPrice = 55.0,
                            Maker = "SparkLife",
                            Price = 50.0,
                            Price100 = 40.0,
                            Price50 = 45.0,
                            Title = "ShineWave"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "A gentle body wash that leaves your skin refreshed and hydrated.",
                            ISBN = "PG987654321",
                            ImageUrl = "",
                            ListPrice = 40.0,
                            Maker = "CleanseCo",
                            Price = 35.0,
                            Price100 = 25.0,
                            Price50 = 30.0,
                            Title = "PureGlow"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "A soft and nourishing facial cream for smooth and glowing skin.",
                            ISBN = "ST111223344",
                            ImageUrl = "",
                            ListPrice = 65.0,
                            Maker = "VelvetSkin",
                            Price = 60.0,
                            Price100 = 50.0,
                            Price50 = 55.0,
                            Title = "SoftTouch"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Description = "A refreshing deodorant spray that keeps you fresh all day long.",
                            ISBN = "CS554433221",
                            ImageUrl = "",
                            ListPrice = 20.0,
                            Maker = "LushCare",
                            Price = 18.0,
                            Price100 = 14.0,
                            Price50 = 16.0,
                            Title = "ClearSpark"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 6,
                            Description = "A shaving gel that provides a smooth and irritation-free shave.",
                            ISBN = "FC998877665",
                            ImageUrl = "",
                            ListPrice = 35.0,
                            Maker = "SharpEdge",
                            Price = 30.0,
                            Price100 = 25.0,
                            Price50 = 28.0,
                            Title = "FreshCut"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            Description = "A long-lasting nail polish with vibrant colors and a glossy finish.",
                            ISBN = "GN332211445",
                            ImageUrl = "",
                            ListPrice = 15.0,
                            Maker = "NailArt",
                            Price = 13.0,
                            Price100 = 10.0,
                            Price50 = 12.0,
                            Title = "GlowNail"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            Description = "A fresh and uplifting fragrance that is perfect for daily wear.",
                            ISBN = "EV776655443",
                            ImageUrl = "",
                            ListPrice = 50.0,
                            Maker = "ScentAura",
                            Price = 45.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "EauVibe"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 9,
                            Description = "A hydrating lip balm with a smooth texture and subtle scent.",
                            ISBN = "SK223344556",
                            ImageUrl = "",
                            ListPrice = 10.0,
                            Maker = "LipsCare",
                            Price = 9.0,
                            Price100 = 7.0,
                            Price50 = 8.0,
                            Title = "SoftKiss"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 10,
                            Description = "A nourishing hand cream that keeps your skin soft and hydrated.",
                            ISBN = "HH556677889",
                            ImageUrl = "",
                            ListPrice = 18.0,
                            Maker = "SkinGuard",
                            Price = 16.0,
                            Price100 = 12.0,
                            Price50 = 14.0,
                            Title = "HandHeal"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 12,
                            Description = "A rejuvenating eye cream that targets puffiness and dark circles.",
                            ISBN = "EL998877665",
                            ImageUrl = "",
                            ListPrice = 45.0,
                            Maker = "VisionGlow",
                            Price = 40.0,
                            Price100 = 30.0,
                            Price50 = 35.0,
                            Title = "EyeLuxe"
                        });
                });

            modelBuilder.Entity("Beautique.Models.Product", b =>
                {
                    b.HasOne("Beautique.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
